In [64]:
import numpy as np

In [65]:
#creat numpy array using list
a = np.array([1,2,3,4])

In [66]:
a

array([1, 2, 3, 4])

In [67]:
# creat numpy using arange()
a1 = np.arange(12).reshape(3,4)

In [68]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a1[::2] # this mean all row skipe 1 by 1

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [70]:
a1[::,1:4:2] # this mean all row and 1st colummn to 3rd cloumnn exsecpt jump 1 column 

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [71]:
a1[::,::2] # this mean all row and 2nd colummn to 4th cloumnn exsecpt jump 1 column 

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [72]:
a1[::,1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [73]:
a1[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [74]:
a1[::2,1:4:2]

array([[ 1,  3],
       [ 9, 11]])

In [75]:
a1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
a1[1]

array([4, 5, 6, 7])

In [77]:
a1[1,0:4:3]

array([4, 7])

In [78]:
a1[1,::3]

array([4, 7])

In [79]:
a1[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [80]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
a1[:2,1:] # 3rower ager sob & 1st colummn er porer sob 

array([[1, 2, 3],
       [5, 6, 7]])

In [82]:
a3 = np.arange(27).reshape(3,3,3)

In [83]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [85]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [86]:
a3[0,1,:]

array([3, 4, 5])

In [87]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [88]:
a3[1,::,1]

array([10, 13, 16])

In [89]:
a3[1,:,1]

array([10, 13, 16])

In [90]:
a3[2,1:]

array([[21, 22, 23],
       [24, 25, 26]])

In [91]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [92]:
a3[0,0,::2] # :: it's mean all

array([0, 2])

In [93]:
a3[2,0,::2]

array([18, 20])

In [94]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## iterating

In [95]:
a

array([1, 2, 3, 4])

In [96]:
for i in a:
    print(i)

1
2
3
4


In [97]:
for i in a1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [98]:
for i in a1:
    for j in i:
        print(j)
    print()

0
1
2
3

4
5
6
7

8
9
10
11



In [99]:
for i in np.nditer(a1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


# Transpose

In [100]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
np.transpose(a1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [102]:
a1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Ravel
In NumPy, ravel() is a function that returns a flattened, one-dimensional array containing the elements of the input array. The original array remains unchanged. It is a convenient way to convert a multi-dimensional array into a flat, one-dimensional array.

In [103]:
a1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# stacking

In [104]:
b = np.arange(12).reshape(3,4)

In [105]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
b1 = np.arange(12,24).reshape(3,4)

In [107]:
b1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### horizontal stacking

In [108]:
np.hstack((b,b1))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

### vartical stacking

In [109]:
np.vstack((b,b1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### horaizontal splitting

In [110]:
np.hsplit(b,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

### vertical splitting

In [111]:
np.vsplit(b1,2)

ValueError: array split does not result in an equal division

In [112]:
np.vsplit(b1,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

### Numpy array vs Python lists

In [113]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

2.6714186668395996


In [114]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.11645841598510742


In [115]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [116]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000104

### Advanced Indexing

In [117]:
# Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [118]:
a[1,2]

6

In [119]:
# Fancy Indexing
a1 = np.arange(12).reshape(4,3)

In [120]:
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [121]:
a1[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [122]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [123]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [124]:
a[[0,1,3,5]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [125]:
a[[0,1,3,5],[0,2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (2,) 

In [ ]:
a[:,[0,2,3]]

# boolean indexing

In [ ]:
a = np.random.randint(1,100,24).reshape(6,4)

In [ ]:
a

In [ ]:
# find all number >50
a>50 # this is call boolean array

In [ ]:
a[a>50] # this is call boolean indexing

In [ ]:
# find out even number 
a[a%2==0]

In [ ]:
# find all number geterthan 50 and even
a[(a>50)&(a%2==0)]

In [ ]:
# find all number not divisible by ?
